. $C0RC_SCRIPT_DIR/func-bck.sh
. $C0RC_SCRIPT_DIR/func-git.sh
. $C0RC_SCRIPT_DIR/func-kde-plasma.sh
. $C0RC_SCRIPT_DIR/func-ramfs.sh
. $C0RC_SCRIPT_DIR/func-rand.sh
. $C0RC_SCRIPT_DIR/func-sec-gpg.sh
. $C0RC_SCRIPT_DIR/func-sec.sh
. $C0RC_SCRIPT_DIR/func-srch.sh
. $C0RC_SCRIPT_DIR/func-ssh-gpg.sh
